
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(grid)
library(gridExtra)
```

```{r}
# setwd("~/Desktop/mice_behavior_capstone/process_data/results")
df <- read.csv('all_the_data.csv')
df$count  = 1 

df <- df %>% filter(mouse_details_sex %in% c('F', 'M')) %>%
             mutate(gender = if_else(mouse_details_sex == 'F', 'Female', 'Male'))

df$mouse_details_strain <- factor(df$mouse_details_strain, levels = c('BW', 'PO', 'BWPOF1', 'BWPOF2'))
```

```{r}
col_names = colnames(df[c(6:220)])
```


```{r}
df2 <- df %>% filter(mouse_details_strain %in% c('BW', 'PO'))
is.na(df2) <- df2==''

var = 'fraction_in_arms_closed_and_middle'

dodge <- position_dodge(width = .9)
ggplot(df2, aes_string(x = 'mouse_details_strain', y= var, color = 'gender')) + 
        geom_violin() + 
        geom_point(alpha = .3, position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.9), width  = .1 ) +
        geom_boxplot(width=0.1,  outlier.colour=NA, position = dodge) +
        theme_minimal() + 
        xlab("Strain") + 
        ylab(var) +
        theme(plot.title = element_text(hjust = 0.5))

t.test(fraction_in_arms_closed_and_middle ~ mouse_details_strain, data = df2)
#ggsave('plots/boxplt_closedAndMid.pdf')
```





```{r}
vio_plot <- function(var){
  
  dodge <- position_dodge(width = .9)
  p<- ggplot(df2, aes_string(x = 'mouse_details_strain', y= var, color = 'gender')) + 
          geom_violin() + 
          geom_point(alpha = .3, position = position_jitterdodge(), width  = .1 ) +
          geom_boxplot(width=0.1,  outlier.colour=NA, position = dodge) +
          theme_minimal() + 
          xlab("Strain") + 
          ylab(var) +
          theme(plot.title = element_text(hjust = 0.5))
  
  print(p)
  
  # ggsave(paste('violin_plots/',var, '.pdf',sep = ''))
  
}
```


```{r}
cols <- Filter(function(x) !any(grepl("mouse_details", x)), colnames(df))               
rem <- c("X", "inner_directory", "count", "gender")
cols <- cols[which(!cols %in% rem)]
```

```{r}
for(i in cols){
  vio_plot(i)
}
```


```{r}
do_t_tests <- function(var){
  df3 <- df %>% filter(mouse_details_strain %in% c('BW', 'PO'))
  
  df3 <- df3 %>%
    select(var, mouse_details_strain) %>%
    filter(!is.na(df3[, var]))
  
  df3[, var] <- as.numeric(as.character(df3[, var]))
  
  print(var)
  
  # ggsave(paste('violin_plots/',var, '.pdf',sep = ''))
  # t.test( ~ mouse_details_strain, data = df2)
  print(t.test(df3[, var] ~ df3[, 'mouse_details_strain']))
}
```

```{r}
for(i in cols){
  do_t_tests(i)
}
```

```{r}
df3 <- df %>% filter(mouse_details_strain %in% c('BW', 'PO'))
  is.na(df3) <- df3==''
  
df3 <- df3 %>%
  select(active_fraction_CL, mouse_details_strain) %>%
  filter(!is.na(df3[, 'active_fraction_CL']))

df3$active_fraction_CL <- as.numeric(as.character(df3$active_fraction_CL))

t.test(df3[, 'active_fraction_CL'] ~ df3[, 'mouse_details_strain'])
```